version: '3'

services:
  nginx:
    build:
      context: ./dependencies/nginx/
      dockerfile: Dockerfile-dev
    container_name: nginx-front
    image: gustavofranca/simple-ecommerce-nginx
    ports:
      - "8080:80"
    command: ["nginx", "-g", "daemon off;"]
    restart: always

